### ISSUE TITLE
Redactar CU de reservas

### ISSUE THREAD

**Issue by komalakd** [komalakd/euskadi#3]
Ya que es el principal ABM de la aplicación combiene tenerlo definido cuanto antes.

**Comment by komalakd** [comment]
Para cuando el CU Edu? jajaj

**Comment by v-dual** [comment]
Que no te llegó?

Jaj, vale la pena hacer un producto de eso?

**Comment by v-dual** [comment]
Es mucho trabajo para hacer un producto de esto? Si tenes ganas podríamos
ponernos a trabajar para conseguir un nuevo cliente y tratar de terminar el
trabajo...

2015-12-02 17:07 GMT-03:00 komalakd <notifications@github.com>:
